### PR TITLE
docs: Update about.md

### LINKED ISSUE #17: Update `about.md` page

### PR DESCRIPTION
**Pull request by TamkeenFatima**
# Checklist

- [x] fixes #17 
- [x] Passes `Semantic Pull Request` and `TypoCheck`
- [ ] New docs are listed in `README.md`
- [ ] New docs are listed in `index.md`
- [ ] Updated table of content
- [ ] Updated nav links in mkdocs.yml

---

## PR description

1. Add background information
2. Add achievements
3. Add vehicle information

### CODE REVIEW

**Comment by pnijhara** [comment]
Nice work @TamkeenFatima. Checks are failing because you have not written the PR title correctly. See other closed PR and edit your PR title again. Also, update PR descrition.

**Comment by TamkeenFatima** [comment]
Done!

**Comment by pnijhara** [comment]
Some more changes required!
Link this file in `index.md` and `README.md`.

**Comment by TamkeenFatima** [comment]
Please elaborate!
Do we need to link `about.md` to `index.md` and `README.md`?

**Comment by TamkeenFatima** [comment]
Completed the checklist

**Comment by pnijhara** [comment]
> Please elaborate!
> Do we need to link `about.md` to `index.md` and `README.md`?

Exactly! Make a place for this in `index.md` and `README.md` and write a short paragraph about us followed by a link to this file.

**Comment by pnijhara** [comment]
> Completed the checklist

If you think points are not required for you then leave them as it is. You are not allowed to strike them down. Things do not work this way.

**Comment by TamkeenFatima** [comment]
> > Please elaborate!
> > Do we need to link `about.md` to `index.md` and `README.md`?
> 
> Exactly! Make a place for this in `index.md` and `README.md` and write a short paragraph about us followed by a link to this file.

Ok, if you say so.
I was thinking that our nav-bar wouldn't be required then! Also, `index.md` and `readme.md` contain complete documentation about the project, and `about.md` contains the description of the club.

**Comment by TamkeenFatima** [comment]
> > Completed the checklist
> 
> If you think points are not required for you then leave them as it is. You are not allowed to strike them down. Things do not work this way.

Sorry, I didn't know that. I thought that was required to be done to complete the checklist.

**Comment by pnijhara** [comment]
> > > Please elaborate!
> > > Do we need to link `about.md` to `index.md` and `README.md`?
> > 
> > 
> > Exactly! Make a place for this in `index.md` and `README.md` and write a short paragraph about us followed by a link to this file.
> 
> Ok, if you say so.
> I was thinking that our nav-bar wouldn't be required then! Also, `index.md` and `readme.md` contain complete documentation about the project, and `about.md` contains the description of the club.

Leave it for now!
Thanks for the contribution!

**Comment by pnijhara** [comment]
@TamkeenFatima About us content looks awesome, especially that table in the hosted version. Nice Work!
Pick some more issues.

**Comment by TamkeenFatima** [comment]
> @TamkeenFatima About us content looks awesome, especially that table in the hosted version. Nice Work!
> Pick some more issues.

Thank you @pnijhara bhai.

**Comment by TamkeenFatima** [comment]
> Pick some more issues.

Sure

**Pull request merged**
