### PR TITLE
feat: Add tabs feature

### LINKED ISSUE #73: Add tabs feature in hosted Docs
For improved navigation
(Details in #68 )

### PR DESCRIPTION
**Pull request by TamkeenFatima**
# Checklist

- [x] fixes #73 
- [x] Passes `Semantic Pull Request` and `TypoCheck`
- [ ] New docs are listed in `README.md`
- [ ] New docs are listed in `index.md`
- [ ] Updated table of content
- [ ] Updated nav links in mkdocs.yml

---

## PR description

Add tabs feature to `mkdocs.yml`

### CODE REVIEW

**Comment by pnijhara** [comment]
Does the following change need some changes in `requirements.txt`? If yes then update that too. Else this one is good to go.

**Comment by TamkeenFatima** [comment]
No, it's a feature of 'materials for mkdocs' and doesn't have any special requirements.
I forgot to mention, this feature works only on large screens (laptop/desktop), while on mobile screen, we will have the old menu.

**Comment by TamkeenFatima** [comment]
Should I add [instant](https://squidfunk.github.io/mkdocs-material/getting-started/#instant-loading) feature as well?

**Comment by pnijhara** [comment]
Yes! Add that too!

**Pull request merged**
