### PR TITLE
docs: Student reports (marketing)

### PR DESCRIPTION
**Pull request by syedjawadakhtar**
# Checklist

- [ ] fixes #xxxx
- [x] Passes `Semantic Pull Request` and `TypoCheck`
- [x] New docs are listed in `README.md`
- [ ] New docs are listed in `index.md`
- [ ] Updated table of content
- [ ] Updated nav links in mkdocs.yml

---

## PR description

Write a brief note here what does your PR changes.
1. Add link to students report in README.md
2. Add students_Reports folder
3. Add students_Reports.md index for student reports
4. Add reports of Aditi and Sabeela

### CODE REVIEW

**Comment by pnijhara** [comment]
Should we include these links in nav-bar?

I think we should include! This can make navigation through files easier.

**Comment by syedjawadakhtar** [comment]
Yup that's a good idea. I'll add that in each team.

**Comment by pnijhara** [comment]
Please update the 2 PRs.

**Comment by syedjawadakhtar** [comment]
I have updated #59. This PR was only for the marketing team. Please the #59

**Comment by pnijhara** [comment]
Still, you can add sub-points in the navigation bar.

**Comment by syedjawadakhtar** [comment]
Sub points like? Elaborate

**Comment by pnijhara** [comment]
```yaml
 Marketing:
    - Index: marketing/README.md
    - Alumni Relations: marketing/alumni_relations.md
    - Creative Coordinator: marketing/creative_Coordinator.md
    - Social media manager: marketing/Social_Media_Manager.md
    - Treasurer: marketing/treasurer.md
    - Sponsorship Coordinator: marketing/sponsorship.md
    - Event Manager: marketing/event_Manager.md
    - Student Reports:
           - Student reports: students.md
           - Report1: Report1.md
           - Report2: Report2.md
```

give proper names to reports according to your convenience.

**Comment by syedjawadakhtar** [comment]
Sub points would be nice but adding it would increase a lot for a nav bar. Navigating to the student.md would be enough for anyone to go the list of reports displayed there.
I think only the "Students Report" is enough in each teams nav-bar.

**Comment by pnijhara** [comment]
Give it a try for now!
Will see if this does not work, will remove the thread.

Moreover, navigation bar is a toggle list. No of links should not hinder the situation.

**Comment by syedjawadakhtar** [comment]
Alright I'll add in the other PR #59. Pull this one for now.

**Comment by pnijhara** [comment]
> I think only the "Students Report" is enough in each teams nav-bar.

Agreed!
I think we should not add the links to the nav bar.
But this can decrease ease of navigation.

But for now we should remove the links.

**Comment by syedjawadakhtar** [comment]
Yup! Can you do me a favor by romving the links for now?
Then I'll ask the volunteers to add their and others report in it.

**Pull request merged**
