### PR TITLE
docs: Update marketing docs 

### PR DESCRIPTION
**Pull request by syedjawadakhtar**
# Checklist

- [x] Updates #31 
- [x] Passes `Semantic Pull Request` and `TypoCheck`
- [ ] New docs are listed in `README.md`
- [x] New static folder in marketing docs
- [ ] New docs are listed in `index.md`
- [ ] Updated table of content
- [x] Updated nav links in mkdocs.yml

---

## PR description
1. Add images to sponsorship.md
2. Add offline_CF.md
3. Add online_CF.md
4. Add static folder with images

### CODE REVIEW

**Comment by pnijhara** [comment]
Looks Good to me!
Please add these files in the respective README.

**Comment by syedjawadakhtar** [comment]
They are meant to be navigated through the sponsorship.md only. Adding in README.md would just cramp the Table of contents.

**Comment by pnijhara** [comment]
Then how will the reader navigate through these files? Add sub points in the table content under sponsorship point.
The links should be added to the navigation bar as well.

**Comment by syedjawadakhtar** [comment]
Thanks for pointing out that to me.

**Review by pnijhara — APPROVED** [review]

**Pull request merged**
